### DISCUSSION TITLE
一次性解决反代后PMail的证书问题

### DISCUSSION THREAD

**Discussion by wheat0r** [Jinnrry/PMail#279] [Show and tell]
首先我们知道当PMail的web运行在反代之后的时候，pmail内部的自动证书流程并不好用，http-01是无法使用的，dns-01需要手动配置TXT记录。为了简化这个流程，把可以把dns-01交给acme.sh来做。
web的证书则由反代那边解决。

首先写一个docker-compose.yaml:
```
services:
    pmail:
        image: 'reg-ghcr.naipiapp.uk/jinnrry/pmail:latest'
        container_name: pmail
        restart: unless-stopped
        volumes:
            - ./config:/work/config
        ports:
            - '993:993'
            - '995:995'
            - '587:587'
            - '465:465'
            - '110:110'
            - '25:25'
            #- '80xx:80'
        networks:
            - "reverse-proxy"

    acme-sh:
        image: neilpang/acme.sh
        container_name: acme.sh
        volumes:
            - ./config/acme:/acme.sh
        environment:
            - Tencent_SecretId=${My_SecretId}
            - Tencent_SecretKey=${My_SecretKey}
        command: daemon
        stdin_open: true
        tty: true
        restart: unless-stopped
        networks:
            - "reverse-proxy"

networks:
    reverse-proxy:
      external: true
```
简单介绍一下，我这边把pmail的容器和反代的容器放在了同一个网络里，用容器名就可以实现反代，-p 80实际上不需要配置。我的配置里使用的的腾讯云的API，使用其他DNS服务可以在acme.sh那边寻找文档。

容器运行后，执行`docker exec -it acme.sh sh`到容器内。
直接执行`acme.sh --issue --dns dns_tencent -d smtp.example.com -d imap.example.com -d pop.example.com`完成证书申请和续期。
当然也可以在这里使用其他acme.sh命令，比如使用Let's Encrypt申请证书，而不是ZeroSSL：`acme.sh --set-default-ca --server letsencrypt`

回到PMail的初始化流程最后一步，选择手动管理证书，填写正确的路径（./config/acme/xxx.example.com/）和文件名，PMail即可顺利初始化。

接下来就是把我拦住的25端口问题要各位解决了。
